spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: ${NOTIFICATION_DB_USERNAME:NOTIFICATION_SCHEMA}
    password: ${NOTIFICATION_DB_PASSWORD:NotificationSchema@123}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,info

notification:
  kafka:
    notification-topic: notification-events
    audit-topic: audit-events
