CREATE USER NOTIFICATION_SCHEMA
IDENTIFIED BY "Notification@123";

GRANT CREATE SESSION TO NOTIFICATION_SCHEMA;
GRANT CREATE TABLE TO NOTIFICATION_SCHEMA;
GRANT CREATE SEQUENCE TO NOTIFICATION_SCHEMA;
GRANT CREATE VIEW TO NOTIFICATION_SCHEMA;
GRANT CREATE PROCEDURE TO NOTIFICATION_SCHEMA;
GRANT CREATE TRIGGER TO NOTIFICATION_SCHEMA;
GRANT UNLIMITED TABLESPACE TO NOTIFICATION_SCHEMA;