spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service

  datasource:
    url: ${USER_DB_URL}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.netbanking.user_service


server:
  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always


logging:
  level:
    com.netbanking.user_service: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG


eureka:
  client:
    enabled: false


services:
  account-service:
    url: http://localhost:8083