CREATE USER USER_SCHEMA
IDENTIFIED BY "UserSchema@123";

GRANT CREATE SESSION TO USER_SCHEMA;

GRANT CREATE TABLE TO USER_SCHEMA;
GRANT CREATE SEQUENCE TO USER_SCHEMA;
GRANT CREATE VIEW TO USER_SCHEMA;
GRANT CREATE PROCEDURE TO USER_SCHEMA;
GRANT CREATE TRIGGER TO USER_SCHEMA;

GRANT UNLIMITED TABLESPACE TO USER_SCHEMA;
