CREATE USER TRANSACTION_SCHEMA
IDENTIFIED BY "Transaction@123";

-- Basic session and object privileges
GRANT CREATE SESSION TO TRANSACTION_SCHEMA;
GRANT CREATE TABLE TO TRANSACTION_SCHEMA;
GRANT CREATE SEQUENCE TO TRANSACTION_SCHEMA;
GRANT CREATE VIEW TO TRANSACTION_SCHEMA;
GRANT CREATE PROCEDURE TO TRANSACTION_SCHEMA;
GRANT CREATE TRIGGER TO TRANSACTION_SCHEMA;
GRANT UNLIMITED TABLESPACE TO TRANSACTION_SCHEMA;