spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:FREE
    username: TRANSACTION_SCHEMA
    password: change-me
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8083

clients:
  account-service:
    url: http://localhost:8082
  user-service:
    url: http://localhost:8081

kafka:
  topic:
    transaction-events: transaction-events

logging:
  level:
    com.netbanking.transaction: INFO
