-- ============================================================
-- AUTH SERVICE SCHEMA USER
-- Run this as SYS or SYSTEM
-- ============================================================

CREATE USER AUTH_SCHEMA
IDENTIFIED BY "Auth@123";

GRANT CREATE SESSION TO AUTH_SCHEMA;
GRANT CREATE TABLE TO AUTH_SCHEMA;
GRANT CREATE SEQUENCE TO AUTH_SCHEMA;
GRANT CREATE VIEW TO AUTH_SCHEMA;
GRANT CREATE PROCEDURE TO AUTH_SCHEMA;
GRANT CREATE TRIGGER TO AUTH_SCHEMA;
GRANT UNLIMITED TABLESPACE TO AUTH_SCHEMA;
