CREATE TABLE ACCOUNT (
    ACCOUNT_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CUSTOMER_ID         VARCHAR2(50) NOT NULL,
    ACCOUNT_NUMBER      VARCHAR2(20) NOT NULL,
    ACCOUNT_TYPE        VARCHAR2(20) NOT NULL,
    ACCOUNT_STATUS      VARCHAR2(30)
                        DEFAULT 'PENDING_APPROVAL' NOT NULL,
    CURRENCY_CODE       VARCHAR2(3)
                        DEFAULT 'INR' NOT NULL,

    CREATED_AT          TIMESTAMP
                        DEFAULT SYSTIMESTAMP NOT NULL,

    UPDATED_AT          TIMESTAMP
                        DEFAULT SYSTIMESTAMP NOT NULL,

    APPROVED_AT         TIMESTAMP,
    CLOSED_AT           TIMESTAMP,
    CLOSURE_REASON      VARCHAR2(500),

    CONSTRAINT PK_ACCOUNT
        PRIMARY KEY (ACCOUNT_ID),

    CONSTRAINT UK_ACCOUNT_NUMBER
        UNIQUE (ACCOUNT_NUMBER),

    CONSTRAINT CK_ACCOUNT_TYPE
        CHECK (
            ACCOUNT_TYPE IN (
                'SAVINGS',
                'CURRENT'
            )
        ),

    CONSTRAINT CK_ACCOUNT_STATUS
        CHECK (
            ACCOUNT_STATUS IN (
                'PENDING_APPROVAL',
                'ACTIVE',
                'FROZEN',
                'BLOCKED',
                'CLOSED',
                'REJECTED'
            )
        )
);


-- ============================================================
-- 3. ACCOUNT_BALANCE
--
-- Stores:
--      Current Balance
--      Available Balance
--      Total Credits
--      Total Debits
-- ============================================================

CREATE TABLE ACCOUNT_BALANCE (
    ACCOUNT_ID              NUMBER NOT NULL,

    CURRENT_BALANCE         NUMBER(19,2)
                            DEFAULT 0 NOT NULL,

    AVAILABLE_BALANCE       NUMBER(19,2)
                            DEFAULT 0 NOT NULL,

    TOTAL_CREDIT            NUMBER(19,2)
                            DEFAULT 0 NOT NULL,

    TOTAL_DEBIT             NUMBER(19,2)
                            DEFAULT 0 NOT NULL,

    VERSION_NO              NUMBER
                            DEFAULT 0 NOT NULL,

    CREATED_AT              TIMESTAMP
                            DEFAULT SYSTIMESTAMP NOT NULL,

    UPDATED_AT              TIMESTAMP
                            DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ACCOUNT_BALANCE
        PRIMARY KEY (ACCOUNT_ID),

    CONSTRAINT FK_BALANCE_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT CK_CURRENT_BALANCE
        CHECK (CURRENT_BALANCE >= 0),

    CONSTRAINT CK_AVAILABLE_BALANCE
        CHECK (AVAILABLE_BALANCE >= 0),

    CONSTRAINT CK_AVAILABLE_CURRENT
        CHECK (AVAILABLE_BALANCE <= CURRENT_BALANCE),

    CONSTRAINT CK_TOTAL_CREDIT
        CHECK (TOTAL_CREDIT >= 0),

    CONSTRAINT CK_TOTAL_DEBIT
        CHECK (TOTAL_DEBIT >= 0),

    CONSTRAINT CK_BALANCE_VERSION
        CHECK (VERSION_NO >= 0)
);


-- ============================================================
-- 4. ACCOUNT_PIN
--
-- NEVER store the 4-digit PIN directly.
-- Store only the password/PIN hash.
-- ============================================================

CREATE TABLE ACCOUNT_PIN (
    ACCOUNT_ID              NUMBER NOT NULL,

    PIN_HASH                VARCHAR2(255) NOT NULL,

    PIN_CREATED_AT          TIMESTAMP
                            DEFAULT SYSTIMESTAMP NOT NULL,

    FAILED_ATTEMPTS         NUMBER
                            DEFAULT 0 NOT NULL,

    LOCKED_UNTIL            TIMESTAMP,

    UPDATED_AT              TIMESTAMP
                            DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ACCOUNT_PIN
        PRIMARY KEY (ACCOUNT_ID),

    CONSTRAINT FK_PIN_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT CK_PIN_FAILED_ATTEMPTS
        CHECK (FAILED_ATTEMPTS >= 0)
);



-- ============================================================
-- 5. ACCOUNT_LEDGER
--
-- Financial ledger owned by ACCOUNT SERVICE.
--
-- Each DEBIT/CREDIT creates a new ledger entry.
-- Ledger rows should NOT be updated/deleted.
-- ============================================================

CREATE TABLE ACCOUNT_LEDGER (
    LEDGER_ID                   NUMBER
                                GENERATED BY DEFAULT AS IDENTITY,

    ACCOUNT_ID                  NUMBER NOT NULL,

    TRANSACTION_REFERENCE       VARCHAR2(100) NOT NULL,

    ENTRY_REFERENCE             VARCHAR2(100) NOT NULL,

    ENTRY_TYPE                  VARCHAR2(10) NOT NULL,

    AMOUNT                      NUMBER(19,2) NOT NULL,

    BALANCE_BEFORE              NUMBER(19,2) NOT NULL,

    BALANCE_AFTER               NUMBER(19,2) NOT NULL,

    AVAILABLE_BALANCE_BEFORE    NUMBER(19,2) NOT NULL,

    AVAILABLE_BALANCE_AFTER     NUMBER(19,2) NOT NULL,

    DESCRIPTION                 VARCHAR2(500),

    CREATED_BY                  VARCHAR2(100),

    CREATED_AT                  TIMESTAMP
                                DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ACCOUNT_LEDGER
        PRIMARY KEY (LEDGER_ID),

    CONSTRAINT FK_LEDGER_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT UK_LEDGER_ENTRY_REF
        UNIQUE (ENTRY_REFERENCE),

    CONSTRAINT CK_LEDGER_ENTRY_TYPE
        CHECK (
            ENTRY_TYPE IN (
                'DEBIT',
                'CREDIT'
            )
        ),

    CONSTRAINT CK_LEDGER_AMOUNT
        CHECK (AMOUNT > 0),

    CONSTRAINT CK_LEDGER_BALANCE_BEFORE
        CHECK (BALANCE_BEFORE >= 0),

    CONSTRAINT CK_LEDGER_BALANCE_AFTER
        CHECK (BALANCE_AFTER >= 0),

    CONSTRAINT CK_LEDGER_AVAIL_BEFORE
        CHECK (AVAILABLE_BALANCE_BEFORE >= 0),

    CONSTRAINT CK_LEDGER_AVAIL_AFTER
        CHECK (AVAILABLE_BALANCE_AFTER >= 0)
);


-- ============================================================
-- 6. ACCOUNT_TYPE_HISTORY
--
-- Used when customer switches:
--
-- SAVINGS -> CURRENT
-- CURRENT -> SAVINGS
--
-- Do not lose the old account type.
-- ============================================================

CREATE TABLE ACCOUNT_TYPE_HISTORY (
    HISTORY_ID          NUMBER
                        GENERATED BY DEFAULT AS IDENTITY,

    ACCOUNT_ID          NUMBER NOT NULL,

    OLD_ACCOUNT_TYPE    VARCHAR2(20) NOT NULL,

    NEW_ACCOUNT_TYPE    VARCHAR2(20) NOT NULL,

    CHANGED_BY          VARCHAR2(100) NOT NULL,

    REASON              VARCHAR2(500),

    CHANGED_AT          TIMESTAMP
                        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ACCOUNT_TYPE_HISTORY
        PRIMARY KEY (HISTORY_ID),

    CONSTRAINT FK_TYPE_HISTORY_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID)
        REFERENCES ACCOUNT(ACCOUNT_ID),

    CONSTRAINT CK_HISTORY_OLD_TYPE
        CHECK (
            OLD_ACCOUNT_TYPE IN (
                'SAVINGS',
                'CURRENT'
            )
        ),

    CONSTRAINT CK_HISTORY_NEW_TYPE
        CHECK (
            NEW_ACCOUNT_TYPE IN (
                'SAVINGS',
                'CURRENT'
            )
        ),

    CONSTRAINT CK_HISTORY_TYPE_CHANGE
        CHECK (
            OLD_ACCOUNT_TYPE <> NEW_ACCOUNT_TYPE
        )
);


-- ============================================================
-- 7. INDEXES
-- ============================================================

CREATE INDEX IDX_ACCOUNT_CUSTOMER_ID
ON ACCOUNT(CUSTOMER_ID);


CREATE INDEX IDX_ACCOUNT_STATUS
ON ACCOUNT(ACCOUNT_STATUS);


CREATE INDEX IDX_ACCOUNT_TYPE
ON ACCOUNT(ACCOUNT_TYPE);


CREATE INDEX IDX_LEDGER_ACCOUNT
ON ACCOUNT_LEDGER(ACCOUNT_ID);


CREATE INDEX IDX_LEDGER_TRANSACTION_REF
ON ACCOUNT_LEDGER(TRANSACTION_REFERENCE);


CREATE INDEX IDX_LEDGER_ACCOUNT_DATE
ON ACCOUNT_LEDGER(ACCOUNT_ID, CREATED_AT);


CREATE INDEX IDX_TYPE_HISTORY_ACCOUNT
ON ACCOUNT_TYPE_HISTORY(ACCOUNT_ID);


-- ============================================================
-- 8. ACCOUNT UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_UPDATED_AT
BEFORE UPDATE ON ACCOUNT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- ============================================================
-- 9. ACCOUNT_BALANCE UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_BALANCE_UPDATED
BEFORE UPDATE ON ACCOUNT_BALANCE
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/


-- ============================================================
-- 10. ACCOUNT_PIN UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_PIN_UPDATED
BEFORE UPDATE ON ACCOUNT_PIN
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/



-- ============================================================
-- 11. PROTECT ACCOUNT LEDGER
--
-- Prevent UPDATE and DELETE.
-- Ledger is append-only.
-- ============================================================

CREATE OR REPLACE TRIGGER TRG_LEDGER_IMMUTABLE
BEFORE UPDATE OR DELETE ON ACCOUNT_LEDGER
BEGIN

    RAISE_APPLICATION_ERROR(
        -20001,
        'ACCOUNT_LEDGER is append-only. UPDATE and DELETE are not allowed.'
    );

END;
/




-- ============================================================
-- 12. ACCOUNT BALANCE VIEW
-- ============================================================

CREATE OR REPLACE VIEW V_ACCOUNT_BALANCE AS
SELECT
    A.ACCOUNT_ID,
    A.CUSTOMER_ID,
    A.ACCOUNT_NUMBER,
    A.ACCOUNT_TYPE,
    A.ACCOUNT_STATUS,
    A.CURRENCY_CODE,
    B.CURRENT_BALANCE,
    B.AVAILABLE_BALANCE,
    B.TOTAL_CREDIT,
    B.TOTAL_DEBIT,
    B.VERSION_NO
FROM ACCOUNT A
JOIN ACCOUNT_BALANCE B
    ON A.ACCOUNT_ID = B.ACCOUNT_ID;


-- ============================================================
-- 13. VERIFY TABLES
-- ============================================================

SELECT TABLE_NAME
FROM USER_TABLES
ORDER BY TABLE_NAME;

SELECT VIEW_NAME
FROM USER_VIEWS;

SELECT
    TRIGGER_NAME,
    STATUS
FROM USER_TRIGGERS
ORDER BY TRIGGER_NAME;


SELECT
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN (
    'ACCOUNT',
    'ACCOUNT_BALANCE',
    'ACCOUNT_LEDGER',
    'ACCOUNT_PIN',
    'ACCOUNT_TYPE_HISTORY'
)
ORDER BY TABLE_NAME, CONSTRAINT_NAME;