-- ============================================================
-- ACCOUNT SERVICE SCHEMA USER
-- Run this as SYS or SYSTEM
-- ============================================================

CREATE USER ACCOUNT_SCHEMA
IDENTIFIED BY "Account@123";

GRANT CREATE SESSION TO ACCOUNT_SCHEMA;

GRANT CREATE TABLE TO ACCOUNT_SCHEMA;

GRANT CREATE SEQUENCE TO ACCOUNT_SCHEMA;

GRANT CREATE VIEW TO ACCOUNT_SCHEMA;

GRANT CREATE PROCEDURE TO ACCOUNT_SCHEMA;

GRANT CREATE TRIGGER TO ACCOUNT_SCHEMA;

GRANT UNLIMITED TABLESPACE TO ACCOUNT_SCHEMA;